### ISSUE TITLE
raw pointers!!!

### ISSUE THREAD

**Issue by ferrislovescpp** [STyPLy/QuickClicker#1]
don't be silly! you can't be going raw!! also what's with the hardcoded racial slur 😭😭😭

**Comment by ferrislovescpp** [comment]
WHERES THE ERROR HANDLING

**Comment by ferrislovescpp** [comment]
i have autism i just realizes this is like 90% lithium lite 😭😭😭 don't be skidding that goofys shit code

**Comment by STyPLy** [comment]
This was a personal project I made for fun, abandoned and put on GitHub. How tf did you find this? Lol
